#pragma once

#include <filesystem>
#include <fstream>
#include <sstream>
#include <memory>

#include "logic/Beatmap.hpp"
#include "logic/TagDivisionSettings.hpp"
#include "logic/DifficultySettings.hpp"

namespace BeatmapProcessor
{
    /// @brief Load a betmap from given path
    /// @param beatmap
    /// @param path 
    /// @return Error message, empty if ok
    std::string load_beatmap(Beatmap &beatmap, std::filesystem::path path);

    /// @brief Save a beatmap to a given path
    /// @param beatmap 
    /// @param path 
    /// @return Error message, empty if ok
    std::string save_beatmap(const Beatmap &beatmap, std::filesystem::path path);

    /// @brief Save beatmaps generated by the `divide_for_tag()` function
    /// @param beatmap_source 
    /// @param beatmaps 
    /// @param folder_path 
    /// @return Error message, empty if ok
    std::string batch_save(const Beatmap &beatmap_source, const std::vector<std::shared_ptr<Beatmap>> beatmaps,
                           std::filesystem::path folder_path);

    std::vector<std::shared_ptr<Beatmap>> divide_for_tag(const Beatmap &beatmap, const std::string &diff_name, 
                                                         const DifficultySettings &ds, const TagDivisionSettings &tds);
};